/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as faucetSol from "./Faucet.sol";
export type { faucetSol };
import type * as ubeSol from "./UBE.sol";
export type { ubeSol };
export type { MedianOracle } from "./MedianOracle";
export type { QuadraticFunding } from "./QuadraticFunding";
export type { RGU } from "./RGU";
