export type {
  DelegationSigningKeyCompartment,
  DelegationSigningPublicKey,
  DeviceCredentialCompartment,
  Identity,
  JsonSafeByteEncoding,
  OperatorAuthorizationTokenCompartment,
  SeaDevicePairCompartment,
  SignInProviderKind,
  SignInSessionCompartment,
  VaultRecord,
  VaultV2,
  WalletBindingCompartment,
  WalletProviderKind
} from './types';
export {
  LEGACY_STORAGE_KEY,
  LEGACY_VAULT_VERSION,
  isOperatorAuthorizationTokenCompartment,
  isSignInSessionCompartment,
  isWalletBindingCompartment,
  isValidIdentity,
  isVaultV2,
  VAULT_VERSION
} from './types';
export {
  clearIdentity,
  loadIdentity,
  loadVaultV2,
  saveIdentity,
  saveVaultV2,
  updateVaultV2
} from './vault';
export { migrateLegacyLocalStorage } from './migrate';
export {
  base64UrlToBytes,
  bytesToBase64Url,
  clearSignInSession,
  clearWalletBinding,
  delegationSigningKey,
  deviceCredential,
  getDelegationSigningPublicKey,
  loadOrCreateDelegationSigningKey,
  loadOrCreateDeviceCredential,
  loadOrCreateSeaDevicePair,
  loadSignInSession,
  loadWalletBinding,
  normalizeWalletAddress,
  normalizeWalletChainId,
  operatorAuthorizationToken,
  publicDelegationSigningKey,
  randomBase64Url,
  rotateDelegationSigningKey,
  rotateDeviceCredential,
  rotateSeaDevicePair,
  rotateStoredDelegationSigningKey,
  saveSignInSession,
  saveWalletBinding,
  seaDevicePair,
  signInSession,
  signInSessionMatchesPrincipal,
  signWithDelegationSigningKey,
  signWithStoredDelegationSigningKey,
  utf8,
  validateDelegationSigningKey,
  validateDelegationSigningPublicKey,
  validateDeviceCredential,
  validateOperatorAuthorizationToken,
  validateSeaDevicePair,
  validateSignInSession,
  validateSignInSessionForRead,
  validateWalletBinding,
  VaultCompartmentError,
  verifyWithDelegationSigningKey,
  verifyWithDelegationSigningPublicKey,
  walletBinding,
  walletBindingMatchesPrincipal,
  type SeaDevicePairInput,
  type SignInSessionInput,
  type WalletBindingInput
} from './compartments';
