import type { StoryClusterCoherenceAuditDataset } from './coherenceAudit';
import type { StoryClusterBenchmarkPairExpectation } from './benchmarkCorpusFixtures';
import { makeBenchmarkItem } from './benchmarkCorpusBuilders';

export const STORYCLUSTER_KNOWN_EVENT_ONGOING_FIXTURE_DATASETS: StoryClusterCoherenceAuditDataset[] = [
  {
    dataset_id: 'fixture-known-event-ongoing-kennedy-center',
    topic_id: 'fixture-known-event-ongoing-kennedy-center',
    items: [
      makeBenchmarkItem(
        'kennedy_center_takeover_episode',
        'pbs-kennedy-closure',
        'Kennedy Center to close for 2 years for renovations in July, Trump says, after wave of cancellations',
        'kennedy-closure-pbs',
        1_770_531_360_000,
        {
          publisher: 'PBS News',
          url: 'https://www.pbs.org/newshour/politics/kennedy-center-to-close-for-2-years-for-renovations-in-july-trump-says-after-wave-of-cancellations',
          canonicalUrl: 'https://www.pbs.org/newshour/politics/kennedy-center-to-close-for-2-years-for-renovations-in-july-trump-says-after-wave-of-cancellations',
          entity_keys: ['kennedy_center_takeover_episode', 'kennedy_center', 'renovation_closure', 'richard_grenell'],
          cluster_text: 'Trump said the Kennedy Center would close for two years for renovations, starting the same Kennedy Center takeover and closure episode that later brought staffing cuts, leadership turmoil, and board conflict.',
        },
      ),
      makeBenchmarkItem(
        'kennedy_center_takeover_episode',
        'ap-kennedy-staff-cuts',
        "Kennedy Center head warns staff of cuts and 'skeletal' staffing during renovation closure",
        'kennedy-staff-cuts-ap',
        1_771_338_164_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/9eb9e9fa2368c3eb6fad1c57a90c3407',
          canonicalUrl: 'https://apnews.com/article/9eb9e9fa2368c3eb6fad1c57a90c3407',
          entity_keys: ['kennedy_center_takeover_episode', 'kennedy_center', 'renovation_closure', 'richard_grenell'],
          cluster_text: 'Richard Grenell warned Kennedy Center staff that the same two-year renovation closure would bring cuts and skeletal staffing.',
        },
      ),
      makeBenchmarkItem(
        'kennedy_center_takeover_episode',
        'ap-kennedy-grenell-step-down',
        'Trump ally Ric Grenell stepping down as Kennedy Center president',
        'kennedy-grenell-step-down-ap',
        1_773_514_126_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/6bf4f74ea5f0e80abf8f9c181cdd431a',
          canonicalUrl: 'https://apnews.com/article/6bf4f74ea5f0e80abf8f9c181cdd431a',
          entity_keys: ['kennedy_center_takeover_episode', 'kennedy_center', 'richard_grenell', 'board_meeting'],
          cluster_text: 'Richard Grenell said he was stepping down as Kennedy Center president during the same Kennedy Center takeover fight over the renovation closure and board control.',
        },
      ),
      makeBenchmarkItem(
        'kennedy_center_takeover_episode',
        'ap-kennedy-board-showdown',
        'A seat at the table, but no vote yet for a Democratic lawmaker in the Kennedy Center board showdown',
        'kennedy-board-showdown-ap',
        1_773_584_235_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/53d19b342753174b9a90b9c21aa9fa0c',
          canonicalUrl: 'https://apnews.com/article/53d19b342753174b9a90b9c21aa9fa0c',
          entity_keys: ['kennedy_center_takeover_episode', 'kennedy_center', 'richard_grenell', 'board_meeting'],
          cluster_text: 'A judge let a Democratic lawmaker attend the same Kennedy Center board showdown tied to Grenell, the renovation closure plan, and Trump’s takeover of the institution.',
        },
      ),
      makeBenchmarkItem(
        'kennedy_center_takeover_commentary',
        'pbs-kennedy-grenell-interview',
        'We cannot have art institutions that lose money: Grenell defends Kennedy Center takeover',
        'kennedy-grenell-interview-pbs',
        1_767_701_380_000,
        {
          publisher: 'PBS News',
          url: 'https://www.pbs.org/newshour/show/we-cannot-have-art-institutions-that-lose-money-grenell-defends-kennedy-center-takeover',
          canonicalUrl: 'https://www.pbs.org/newshour/show/we-cannot-have-art-institutions-that-lose-money-grenell-defends-kennedy-center-takeover',
          entity_keys: ['kennedy_center_takeover_commentary', 'kennedy_center', 'richard_grenell', 'trump_takeover'],
          coverage_role: 'related',
          cluster_text: 'Grenell defended Trump’s Kennedy Center takeover in a PBS interview about the institution’s finances and direction.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-fed-powell',
    topic_id: 'fixture-known-event-ongoing-fed-powell',
    items: [
      makeBenchmarkItem(
        'fed_powell_subpoena_episode',
        'ap-fed-subpoena',
        'Federal Reserve Chair Powell says DOJ has subpoenaed central bank, threatens criminal indictment',
        'fed-subpoena-ap',
        1_768_180_699_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/bf4fc6c690fa248fbc531bc9bc7f1758',
          canonicalUrl: 'https://apnews.com/article/bf4fc6c690fa248fbc531bc9bc7f1758',
          entity_keys: ['fed_powell_subpoena_episode', 'jerome_powell', 'federal_reserve', 'doj_subpoenas', 'building_renovation_probe'],
          cluster_text: 'Jerome Powell said the Justice Department subpoenaed the Federal Reserve over the same building-renovation probe and threatened criminal charges.',
        },
      ),
      makeBenchmarkItem(
        'fed_powell_subpoena_episode',
        'ap-fed-backlash',
        'DOJ investigation of Fed Chair Powell sparks backlash, support for Fed independence',
        'fed-backlash-ap',
        1_768_234_798_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/d87eedf1e35195957f903f9963aeaf99',
          canonicalUrl: 'https://apnews.com/article/d87eedf1e35195957f903f9963aeaf99',
          entity_keys: ['fed_powell_subpoena_episode', 'jerome_powell', 'federal_reserve', 'doj_subpoenas', 'building_renovation_probe'],
          cluster_text: 'The same Justice Department subpoena fight over Federal Reserve building renovations triggered backlash and new defenses of Fed independence.',
        },
      ),
      makeBenchmarkItem(
        'fed_powell_subpoena_episode',
        'ap-fed-judge-quash',
        "Judge quashes subpoenas in Justice Department's investigation of Fed chair Jerome Powell",
        'fed-judge-quash-ap',
        1_773_509_513_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/0fdd36447a6aa8ae3e7125930d03950f',
          canonicalUrl: 'https://apnews.com/article/0fdd36447a6aa8ae3e7125930d03950f',
          entity_keys: ['fed_powell_subpoena_episode', 'jerome_powell', 'federal_reserve', 'doj_subpoenas', 'building_renovation_probe'],
          cluster_text: 'A federal judge quashed the same Justice Department subpoenas aimed at Jerome Powell and the Federal Reserve building-renovation probe.',
        },
      ),
      makeBenchmarkItem(
        'fed_powell_subpoena_explainer',
        'ap-fed-what-we-know',
        "Bringing charges against the Fed: What we do (and don't) know",
        'fed-explainer-ap',
        1_768_245_330_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/b5676bc638f04b3b528372b59673d804',
          canonicalUrl: 'https://apnews.com/article/b5676bc638f04b3b528372b59673d804',
          entity_keys: ['fed_powell_subpoena_explainer', 'jerome_powell', 'federal_reserve', 'doj_subpoenas'],
          coverage_role: 'related',
          cluster_text: 'An AP explainer laid out the legal theories and open questions around the Justice Department pressure campaign against Jerome Powell.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-flag-burn-order-fallout',
    topic_id: 'fixture-known-event-ongoing-flag-burn-order-fallout',
    items: [
      makeBenchmarkItem(
        'white_house_flag_burning_episode',
        'ap-flag-ban-order',
        'Trump moves to ban flag burning despite Supreme Court ruling that Constitution allows it',
        'flag-ban-order-ap',
        1_768_995_600_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/flag-burning-trump-order-ban',
          canonicalUrl: 'https://apnews.com/article/flag-burning-trump-order-ban',
          entity_keys: [
            'white_house_flag_burning_episode',
            'white_house_flag_burning_case',
            'american_flag',
            'white_house',
            'jan_carey',
            'flag_burning_order',
          ],
          cluster_text:
            'Trump announced a new push to ban flag burning after the Jan. Carey White House flag-burning case, setting the policy and legal crackdown that later collapsed in court.',
        },
      ),
      makeBenchmarkItem(
        'white_house_flag_burning_episode',
        'ap-flag-case-dismissal',
        'Feds move to dismiss charges against Army veteran who burned American flag near White House',
        'flag-case-dismissal-ap',
        1_771_258_400_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/flag-burning-carey-case-dismissed',
          canonicalUrl: 'https://apnews.com/article/flag-burning-carey-case-dismissed',
          entity_keys: [
            'white_house_flag_burning_episode',
            'white_house_flag_burning_case',
            'american_flag',
            'white_house',
            'jan_carey',
            'flag_burning_order',
          ],
          cluster_text:
            'Federal prosecutors moved to dismiss the Jan. Carey White House flag-burning case, direct legal fallout from the same Trump-backed flag-burning crackdown.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-teacher-prank-fallout',
    topic_id: 'fixture-known-event-ongoing-teacher-prank-fallout',
    items: [
      makeBenchmarkItem(
        'teacher_prank_death_episode',
        'ap-prank-adult-charge',
        "Georgia teen charged as an adult in death of teacher hit by car after 'senior prank'",
        'teacher-prank-adult-charge-ap',
        1_746_720_000_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/georgia-teacher-prank-adult-charge',
          canonicalUrl: 'https://apnews.com/article/georgia-teacher-prank-adult-charge',
          entity_keys: [
            'teacher_prank_death_episode',
            'teacher_prank_death_case',
            'adrianne_hutcherson',
            'senior_prank',
            'criminal_charge',
          ],
          cluster_text:
            'Georgia prosecutors charged a teen as an adult after teacher Adrianne Hutcherson was struck and killed during the same senior-prank case.',
        },
      ),
      makeBenchmarkItem(
        'teacher_prank_death_episode',
        'ap-prank-charges-dropped',
        'Charges dropped against teens whose teacher died during toilet paper prank',
        'teacher-prank-charges-dropped-ap',
        1_757_116_800_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/georgia-teacher-prank-charges-dropped',
          canonicalUrl: 'https://apnews.com/article/georgia-teacher-prank-charges-dropped',
          entity_keys: [
            'teacher_prank_death_episode',
            'teacher_prank_death_case',
            'adrianne_hutcherson',
            'senior_prank',
            'criminal_charge',
          ],
          cluster_text:
            'Prosecutors later dropped charges in the same Georgia teacher-prank death case after the earlier adult-charge decision and public scrutiny.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-fani-willis-fallout',
    topic_id: 'fixture-known-event-ongoing-fani-willis-fallout',
    items: [
      makeBenchmarkItem(
        'fani_willis_postdismissal_episode',
        'ap-willis-legal-fees',
        "Trump seeks $6.2 million in legal fees from Fani Willis' office over election interference case",
        'fani-willis-legal-fees-ap',
        1_772_726_400_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/trump-fani-willis-legal-fees',
          canonicalUrl: 'https://apnews.com/article/trump-fani-willis-legal-fees',
          entity_keys: [
            'fani_willis_postdismissal_episode',
            'georgia_trump_election_case',
            'fani_willis',
            'nathan_wade',
            'postdismissal_fallout',
          ],
          cluster_text:
            'Trump sought legal fees from Fani Willis after the collapse of the Georgia election interference case, part of the same post-dismissal fallout episode that later brought legislative pressure and hearings about Nathan Wade.',
        },
      ),
      makeBenchmarkItem(
        'fani_willis_postdismissal_episode',
        'ap-willis-gop-bills',
        'Georgia Republicans push more bills aimed at Fulton County DA Fani Willis',
        'fani-willis-gop-bills-ap',
        1_772_899_200_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/fani-willis-georgia-republicans-bills',
          canonicalUrl: 'https://apnews.com/article/fani-willis-georgia-republicans-bills',
          entity_keys: [
            'fani_willis_postdismissal_episode',
            'georgia_trump_election_case',
            'fani_willis',
            'nathan_wade',
            'postdismissal_fallout',
          ],
          cluster_text:
            'Georgia Republicans advanced new bills targeting Fani Willis as part of the same post-dismissal fallout from the Georgia Trump election case.',
        },
      ),
      makeBenchmarkItem(
        'fani_willis_postdismissal_episode',
        'ap-wade-hearing',
        'State lawmakers grill former special prosecutor Nathan Wade over Georgia Trump election case',
        'nathan-wade-hearing-ap',
        1_773_249_600_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/nathan-wade-hearing-georgia-trump-case',
          canonicalUrl: 'https://apnews.com/article/nathan-wade-hearing-georgia-trump-case',
          entity_keys: [
            'fani_willis_postdismissal_episode',
            'georgia_trump_election_case',
            'fani_willis',
            'nathan_wade',
            'postdismissal_fallout',
          ],
          cluster_text:
            'Lawmakers questioned former special prosecutor Nathan Wade during the same post-dismissal fallout around the Georgia Trump election case and pressure on Fani Willis.',
        },
      ),
    ],
  },
];

export const STORYCLUSTER_KNOWN_EVENT_ONGOING_PAIR_EXPECTATIONS: StoryClusterBenchmarkPairExpectation[] = [
  {
    case_id: 'known-event-ongoing-kennedy-closure-staff-cuts',
    dataset_id: 'fixture-known-event-ongoing-kennedy-center',
    left_source_id: 'pbs-kennedy-closure',
    right_source_id: 'ap-kennedy-staff-cuts',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-kennedy-staff-cuts-grenell-step-down',
    dataset_id: 'fixture-known-event-ongoing-kennedy-center',
    left_source_id: 'ap-kennedy-staff-cuts',
    right_source_id: 'ap-kennedy-grenell-step-down',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-kennedy-grenell-board-showdown',
    dataset_id: 'fixture-known-event-ongoing-kennedy-center',
    left_source_id: 'ap-kennedy-grenell-step-down',
    right_source_id: 'ap-kennedy-board-showdown',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-kennedy-interview-vs-board',
    dataset_id: 'fixture-known-event-ongoing-kennedy-center',
    left_source_id: 'pbs-kennedy-grenell-interview',
    right_source_id: 'ap-kennedy-board-showdown',
    expected_label: 'commentary_on_event',
  },
  {
    case_id: 'known-event-ongoing-fed-subpoena-backlash',
    dataset_id: 'fixture-known-event-ongoing-fed-powell',
    left_source_id: 'ap-fed-subpoena',
    right_source_id: 'ap-fed-backlash',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-fed-subpoena-quash',
    dataset_id: 'fixture-known-event-ongoing-fed-powell',
    left_source_id: 'ap-fed-subpoena',
    right_source_id: 'ap-fed-judge-quash',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-fed-backlash-quash',
    dataset_id: 'fixture-known-event-ongoing-fed-powell',
    left_source_id: 'ap-fed-backlash',
    right_source_id: 'ap-fed-judge-quash',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-fed-explainer-vs-quash',
    dataset_id: 'fixture-known-event-ongoing-fed-powell',
    left_source_id: 'ap-fed-what-we-know',
    right_source_id: 'ap-fed-judge-quash',
    expected_label: 'commentary_on_event',
  },
  {
    case_id: 'known-event-ongoing-flag-ban-vs-dismissal',
    dataset_id: 'fixture-known-event-ongoing-flag-burn-order-fallout',
    left_source_id: 'ap-flag-ban-order',
    right_source_id: 'ap-flag-case-dismissal',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-prank-charge-vs-dismissal',
    dataset_id: 'fixture-known-event-ongoing-teacher-prank-fallout',
    left_source_id: 'ap-prank-adult-charge',
    right_source_id: 'ap-prank-charges-dropped',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-willis-fees-vs-bills',
    dataset_id: 'fixture-known-event-ongoing-fani-willis-fallout',
    left_source_id: 'ap-willis-legal-fees',
    right_source_id: 'ap-willis-gop-bills',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-willis-bills-vs-wade-hearing',
    dataset_id: 'fixture-known-event-ongoing-fani-willis-fallout',
    left_source_id: 'ap-willis-gop-bills',
    right_source_id: 'ap-wade-hearing',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-willis-fees-vs-wade-hearing',
    dataset_id: 'fixture-known-event-ongoing-fani-willis-fallout',
    left_source_id: 'ap-willis-legal-fees',
    right_source_id: 'ap-wade-hearing',
    expected_label: 'same_developing_episode',
  },
];
