import type { StoryClusterCoherenceAuditDataset } from './coherenceAudit';
import type { StoryClusterBenchmarkPairExpectation } from './benchmarkCorpusFixtures';
import { makeBenchmarkItem } from './benchmarkCorpusBuilders';

export const STORYCLUSTER_KNOWN_EVENT_ONGOING_FIXTURE_DATASETS: StoryClusterCoherenceAuditDataset[] = [
  {
    dataset_id: 'fixture-known-event-ongoing-kennedy-center',
    topic_id: 'fixture-known-event-ongoing-kennedy-center',
    items: [
      makeBenchmarkItem(
        'kennedy_center_takeover_episode',
        'pbs-kennedy-closure',
        'Kennedy Center to close for 2 years for renovations in July, Trump says, after wave of cancellations',
        'kennedy-closure-pbs',
        1_770_531_360_000,
        {
          publisher: 'PBS News',
          url: 'https://www.pbs.org/newshour/politics/kennedy-center-to-close-for-2-years-for-renovations-in-july-trump-says-after-wave-of-cancellations',
          canonicalUrl: 'https://www.pbs.org/newshour/politics/kennedy-center-to-close-for-2-years-for-renovations-in-july-trump-says-after-wave-of-cancellations',
          entity_keys: ['kennedy_center_takeover_episode', 'kennedy_center', 'renovation_closure', 'richard_grenell'],
          cluster_text: 'Trump said the Kennedy Center would close for two years for renovations, starting the same Kennedy Center takeover and closure episode that later brought staffing cuts, leadership turmoil, and board conflict.',
        },
      ),
      makeBenchmarkItem(
        'kennedy_center_takeover_episode',
        'ap-kennedy-staff-cuts',
        "Kennedy Center head warns staff of cuts and 'skeletal' staffing during renovation closure",
        'kennedy-staff-cuts-ap',
        1_771_338_164_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/9eb9e9fa2368c3eb6fad1c57a90c3407',
          canonicalUrl: 'https://apnews.com/article/9eb9e9fa2368c3eb6fad1c57a90c3407',
          entity_keys: ['kennedy_center_takeover_episode', 'kennedy_center', 'renovation_closure', 'richard_grenell'],
          cluster_text: 'Richard Grenell warned Kennedy Center staff that the same two-year renovation closure would bring cuts and skeletal staffing.',
        },
      ),
      makeBenchmarkItem(
        'kennedy_center_takeover_episode',
        'ap-kennedy-grenell-step-down',
        'Trump ally Ric Grenell stepping down as Kennedy Center president',
        'kennedy-grenell-step-down-ap',
        1_773_514_126_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/6bf4f74ea5f0e80abf8f9c181cdd431a',
          canonicalUrl: 'https://apnews.com/article/6bf4f74ea5f0e80abf8f9c181cdd431a',
          entity_keys: ['kennedy_center_takeover_episode', 'kennedy_center', 'richard_grenell', 'board_meeting'],
          cluster_text: 'Richard Grenell said he was stepping down as Kennedy Center president during the same Kennedy Center takeover fight over the renovation closure and board control.',
        },
      ),
      makeBenchmarkItem(
        'kennedy_center_takeover_episode',
        'ap-kennedy-board-showdown',
        'A seat at the table, but no vote yet for a Democratic lawmaker in the Kennedy Center board showdown',
        'kennedy-board-showdown-ap',
        1_773_584_235_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/53d19b342753174b9a90b9c21aa9fa0c',
          canonicalUrl: 'https://apnews.com/article/53d19b342753174b9a90b9c21aa9fa0c',
          entity_keys: ['kennedy_center_takeover_episode', 'kennedy_center', 'richard_grenell', 'board_meeting'],
          cluster_text: 'A judge let a Democratic lawmaker attend the same Kennedy Center board showdown tied to Grenell, the renovation closure plan, and Trump’s takeover of the institution.',
        },
      ),
      makeBenchmarkItem(
        'kennedy_center_takeover_commentary',
        'pbs-kennedy-grenell-interview',
        'We cannot have art institutions that lose money: Grenell defends Kennedy Center takeover',
        'kennedy-grenell-interview-pbs',
        1_767_701_380_000,
        {
          publisher: 'PBS News',
          url: 'https://www.pbs.org/newshour/show/we-cannot-have-art-institutions-that-lose-money-grenell-defends-kennedy-center-takeover',
          canonicalUrl: 'https://www.pbs.org/newshour/show/we-cannot-have-art-institutions-that-lose-money-grenell-defends-kennedy-center-takeover',
          entity_keys: ['kennedy_center_takeover_commentary', 'kennedy_center', 'richard_grenell', 'trump_takeover'],
          coverage_role: 'related',
          cluster_text: 'Grenell defended Trump’s Kennedy Center takeover in a PBS interview about the institution’s finances and direction.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-fed-powell',
    topic_id: 'fixture-known-event-ongoing-fed-powell',
    items: [
      makeBenchmarkItem(
        'fed_powell_subpoena_episode',
        'ap-fed-subpoena',
        'Federal Reserve Chair Powell says DOJ has subpoenaed central bank, threatens criminal indictment',
        'fed-subpoena-ap',
        1_768_180_699_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/bf4fc6c690fa248fbc531bc9bc7f1758',
          canonicalUrl: 'https://apnews.com/article/bf4fc6c690fa248fbc531bc9bc7f1758',
          entity_keys: ['fed_powell_subpoena_episode', 'jerome_powell', 'federal_reserve', 'doj_subpoenas', 'building_renovation_probe'],
          cluster_text: 'Jerome Powell said the Justice Department subpoenaed the Federal Reserve over the same building-renovation probe and threatened criminal charges.',
        },
      ),
      makeBenchmarkItem(
        'fed_powell_subpoena_episode',
        'ap-fed-backlash',
        'DOJ investigation of Fed Chair Powell sparks backlash, support for Fed independence',
        'fed-backlash-ap',
        1_768_234_798_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/d87eedf1e35195957f903f9963aeaf99',
          canonicalUrl: 'https://apnews.com/article/d87eedf1e35195957f903f9963aeaf99',
          entity_keys: ['fed_powell_subpoena_episode', 'jerome_powell', 'federal_reserve', 'doj_subpoenas', 'building_renovation_probe'],
          cluster_text: 'The same Justice Department subpoena fight over Federal Reserve building renovations triggered backlash and new defenses of Fed independence.',
        },
      ),
      makeBenchmarkItem(
        'fed_powell_subpoena_episode',
        'ap-fed-judge-quash',
        "Judge quashes subpoenas in Justice Department's investigation of Fed chair Jerome Powell",
        'fed-judge-quash-ap',
        1_773_509_513_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/0fdd36447a6aa8ae3e7125930d03950f',
          canonicalUrl: 'https://apnews.com/article/0fdd36447a6aa8ae3e7125930d03950f',
          entity_keys: ['fed_powell_subpoena_episode', 'jerome_powell', 'federal_reserve', 'doj_subpoenas', 'building_renovation_probe'],
          cluster_text: 'A federal judge quashed the same Justice Department subpoenas aimed at Jerome Powell and the Federal Reserve building-renovation probe.',
        },
      ),
      makeBenchmarkItem(
        'fed_powell_subpoena_explainer',
        'ap-fed-what-we-know',
        "Bringing charges against the Fed: What we do (and don't) know",
        'fed-explainer-ap',
        1_768_245_330_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/b5676bc638f04b3b528372b59673d804',
          canonicalUrl: 'https://apnews.com/article/b5676bc638f04b3b528372b59673d804',
          entity_keys: ['fed_powell_subpoena_explainer', 'jerome_powell', 'federal_reserve', 'doj_subpoenas'],
          coverage_role: 'related',
          cluster_text: 'An AP explainer laid out the legal theories and open questions around the Justice Department pressure campaign against Jerome Powell.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-flag-burn-order-fallout',
    topic_id: 'fixture-known-event-ongoing-flag-burn-order-fallout',
    items: [
      makeBenchmarkItem(
        'white_house_flag_burning_episode',
        'ap-flag-ban-order',
        'Trump moves to ban flag burning despite Supreme Court ruling that Constitution allows it',
        'flag-ban-order-ap',
        1_768_995_600_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/flag-burning-trump-order-ban',
          canonicalUrl: 'https://apnews.com/article/flag-burning-trump-order-ban',
          entity_keys: [
            'white_house_flag_burning_episode',
            'white_house_flag_burning_case',
            'american_flag',
            'white_house',
            'jan_carey',
            'flag_burning_order',
          ],
          cluster_text:
            'Trump announced a new push to ban flag burning after the Jan. Carey White House flag-burning case, setting the policy and legal crackdown that later collapsed in court.',
        },
      ),
      makeBenchmarkItem(
        'white_house_flag_burning_episode',
        'ap-flag-case-dismissal',
        'Feds move to dismiss charges against Army veteran who burned American flag near White House',
        'flag-case-dismissal-ap',
        1_771_258_400_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/flag-burning-carey-case-dismissed',
          canonicalUrl: 'https://apnews.com/article/flag-burning-carey-case-dismissed',
          entity_keys: [
            'white_house_flag_burning_episode',
            'white_house_flag_burning_case',
            'american_flag',
            'white_house',
            'jan_carey',
            'flag_burning_order',
          ],
          cluster_text:
            'Federal prosecutors moved to dismiss the Jan. Carey White House flag-burning case, direct legal fallout from the same Trump-backed flag-burning crackdown.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-teacher-prank-fallout',
    topic_id: 'fixture-known-event-ongoing-teacher-prank-fallout',
    items: [
      makeBenchmarkItem(
        'teacher_prank_death_episode',
        'ap-prank-adult-charge',
        "Georgia teen charged as an adult in death of teacher hit by car after 'senior prank'",
        'teacher-prank-adult-charge-ap',
        1_746_720_000_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/georgia-teacher-prank-adult-charge',
          canonicalUrl: 'https://apnews.com/article/georgia-teacher-prank-adult-charge',
          entity_keys: [
            'teacher_prank_death_episode',
            'teacher_prank_death_case',
            'adrianne_hutcherson',
            'senior_prank',
            'criminal_charge',
          ],
          cluster_text:
            'Georgia prosecutors charged a teen as an adult after teacher Adrianne Hutcherson was struck and killed during the same senior-prank case.',
        },
      ),
      makeBenchmarkItem(
        'teacher_prank_death_episode',
        'ap-prank-charges-dropped',
        'Charges dropped against teens whose teacher died during toilet paper prank',
        'teacher-prank-charges-dropped-ap',
        1_757_116_800_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/georgia-teacher-prank-charges-dropped',
          canonicalUrl: 'https://apnews.com/article/georgia-teacher-prank-charges-dropped',
          entity_keys: [
            'teacher_prank_death_episode',
            'teacher_prank_death_case',
            'adrianne_hutcherson',
            'senior_prank',
            'criminal_charge',
          ],
          cluster_text:
            'Prosecutors later dropped charges in the same Georgia teacher-prank death case after the earlier adult-charge decision and public scrutiny.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-fani-willis-fallout',
    topic_id: 'fixture-known-event-ongoing-fani-willis-fallout',
    items: [
      makeBenchmarkItem(
        'fani_willis_postdismissal_episode',
        'ap-willis-legal-fees',
        "Trump seeks $6.2 million in legal fees from Fani Willis' office over election interference case",
        'fani-willis-legal-fees-ap',
        1_772_726_400_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/trump-fani-willis-legal-fees',
          canonicalUrl: 'https://apnews.com/article/trump-fani-willis-legal-fees',
          entity_keys: [
            'fani_willis_postdismissal_episode',
            'georgia_trump_election_case',
            'fani_willis',
            'nathan_wade',
            'postdismissal_fallout',
          ],
          cluster_text:
            'Trump sought legal fees from Fani Willis after the collapse of the Georgia election interference case, part of the same post-dismissal fallout episode that later brought legislative pressure and hearings about Nathan Wade.',
        },
      ),
      makeBenchmarkItem(
        'fani_willis_postdismissal_episode',
        'ap-willis-gop-bills',
        'Georgia Republicans push more bills aimed at Fulton County DA Fani Willis',
        'fani-willis-gop-bills-ap',
        1_772_899_200_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/fani-willis-georgia-republicans-bills',
          canonicalUrl: 'https://apnews.com/article/fani-willis-georgia-republicans-bills',
          entity_keys: [
            'fani_willis_postdismissal_episode',
            'georgia_trump_election_case',
            'fani_willis',
            'nathan_wade',
            'postdismissal_fallout',
          ],
          cluster_text:
            'Georgia Republicans advanced new bills targeting Fani Willis as part of the same post-dismissal fallout from the Georgia Trump election case.',
        },
      ),
      makeBenchmarkItem(
        'fani_willis_postdismissal_episode',
        'ap-wade-hearing',
        'State lawmakers grill former special prosecutor Nathan Wade over Georgia Trump election case',
        'nathan-wade-hearing-ap',
        1_773_249_600_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/nathan-wade-hearing-georgia-trump-case',
          canonicalUrl: 'https://apnews.com/article/nathan-wade-hearing-georgia-trump-case',
          entity_keys: [
            'fani_willis_postdismissal_episode',
            'georgia_trump_election_case',
            'fani_willis',
            'nathan_wade',
            'postdismissal_fallout',
          ],
          cluster_text:
            'Lawmakers questioned former special prosecutor Nathan Wade during the same post-dismissal fallout around the Georgia Trump election case and pressure on Fani Willis.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-eric-adams-dismissal',
    topic_id: 'fixture-known-event-ongoing-eric-adams-dismissal',
    items: [
      makeBenchmarkItem(
        'eric_adams_corruption_dismissal_episode',
        'reuters-adams-doj-dismissal',
        'US Justice Department seeks dismissal of corruption case against New York Mayor Eric Adams',
        'eric-adams-doj-dismissal-reuters',
        1_739_201_400_000,
        {
          publisher: 'Reuters',
          url: 'https://www.reuters.com/world/us/us-justice-department-seeks-dismissal-corruption-case-against-new-york-mayor-eric-adams-2025-02-14/',
          canonicalUrl:
            'https://www.reuters.com/world/us/us-justice-department-seeks-dismissal-corruption-case-against-new-york-mayor-eric-adams-2025-02-14/',
          entity_keys: [
            'eric_adams_corruption_dismissal_episode',
            'eric_adams',
            'corruption_case',
            'doj_dismissal_motion',
            'new_york_mayor',
          ],
          cluster_text:
            'The Justice Department moved to dismiss the corruption case against Eric Adams, beginning the same legal-dismissal episode that later brought court scrutiny and a formal dismissal.',
        },
      ),
      makeBenchmarkItem(
        'eric_adams_corruption_dismissal_episode',
        'reuters-adams-judge-weighs-dismissal',
        'Judge cancels Eric Adams trial, weighs DOJ request to dismiss charges',
        'eric-adams-judge-weighs-dismissal-reuters',
        1_739_883_600_000,
        {
          publisher: 'Reuters',
          url: 'https://www.reuters.com/world/us/judge-cancels-eric-adams-trial-weighs-doj-request-dismiss-charges-2025-02-21/',
          canonicalUrl:
            'https://www.reuters.com/world/us/judge-cancels-eric-adams-trial-weighs-doj-request-dismiss-charges-2025-02-21/',
          entity_keys: [
            'eric_adams_corruption_dismissal_episode',
            'eric_adams',
            'corruption_case',
            'doj_dismissal_motion',
            'new_york_mayor',
          ],
          cluster_text:
            'A federal judge paused Eric Adams trial proceedings while weighing the same Justice Department dismissal request in the corruption case.',
        },
      ),
      makeBenchmarkItem(
        'eric_adams_corruption_dismissal_episode',
        'reuters-adams-case-dismissed',
        'Judge dismisses corruption case against New York Mayor Eric Adams',
        'eric-adams-case-dismissed-reuters',
        1_743_249_600_000,
        {
          publisher: 'Reuters',
          url: 'https://www.reuters.com/world/us/judge-dismisses-corruption-case-against-new-york-mayor-eric-adams-2025-04-02/',
          canonicalUrl:
            'https://www.reuters.com/world/us/judge-dismisses-corruption-case-against-new-york-mayor-eric-adams-2025-04-02/',
          entity_keys: [
            'eric_adams_corruption_dismissal_episode',
            'eric_adams',
            'corruption_case',
            'doj_dismissal_motion',
            'new_york_mayor',
          ],
          cluster_text:
            'The judge formally dismissed the corruption case against Eric Adams, closing the same dismissal episode that started with the Justice Department motion and court review.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-mahmoud-khalil',
    topic_id: 'fixture-known-event-ongoing-mahmoud-khalil',
    items: [
      makeBenchmarkItem(
        'mahmoud_khalil_detention_episode',
        'reuters-khalil-new-jersey-challenge',
        'Mahmoud Khalil can challenge detention in New Jersey, appeals court says',
        'mahmoud-khalil-new-jersey-challenge-reuters',
        1_754_409_600_000,
        {
          publisher: 'Reuters',
          url: 'https://www.reuters.com/world/us/mahmoud-khalil-can-challenge-detention-new-jersey-appeals-court-says-2025-08-04/',
          canonicalUrl:
            'https://www.reuters.com/world/us/mahmoud-khalil-can-challenge-detention-new-jersey-appeals-court-says-2025-08-04/',
          entity_keys: [
            'mahmoud_khalil_detention_episode',
            'mahmoud_khalil',
            'columbia_activist',
            'deportation_case',
            'immigration_detention',
          ],
          cluster_text:
            'An appeals court said Mahmoud Khalil could challenge his detention in New Jersey in the same deportation-and-detention legal episode arising from the Trump administration case against the Columbia activist.',
        },
      ),
      makeBenchmarkItem(
        'mahmoud_khalil_detention_episode',
        'reuters-khalil-can-be-deported',
        'US judge says Trump administration can deport Columbia activist Mahmoud Khalil',
        'mahmoud-khalil-can-be-deported-reuters',
        1_749_945_600_000,
        {
          publisher: 'Reuters',
          url: 'https://www.reuters.com/world/us/us-judge-says-trump-administration-can-deport-columbia-activist-mahmoud-khalil-2025-06-13/',
          canonicalUrl:
            'https://www.reuters.com/world/us/us-judge-says-trump-administration-can-deport-columbia-activist-mahmoud-khalil-2025-06-13/',
          entity_keys: [
            'mahmoud_khalil_detention_episode',
            'mahmoud_khalil',
            'columbia_activist',
            'deportation_case',
            'immigration_detention',
          ],
          cluster_text:
            'A judge said the Trump administration could deport Mahmoud Khalil in the same legal episode over the Columbia activist detention and deportation fight.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-abrego-garcia',
    topic_id: 'fixture-known-event-ongoing-abrego-garcia',
    items: [
      makeBenchmarkItem(
        'abrego_garcia_wrongful_deportation_episode',
        'reuters-abrego-no-detention-before-trial',
        'Judge says wrongfully deported Abrego Garcia should not be detained before trial',
        'abrego-no-detention-before-trial-reuters',
        1_755_446_400_000,
        {
          publisher: 'Reuters',
          url: 'https://www.reuters.com/world/us/judge-says-wrongfully-deported-abrego-garcia-should-not-be-detained-before-trial-2025-08-16/',
          canonicalUrl:
            'https://www.reuters.com/world/us/judge-says-wrongfully-deported-abrego-garcia-should-not-be-detained-before-trial-2025-08-16/',
          entity_keys: [
            'abrego_garcia_wrongful_deportation_episode',
            'kilmar_abrego_garcia',
            'wrongful_deportation_case',
            'pretrial_detention',
            'el_salvador_return',
          ],
          cluster_text:
            'A judge said Kilmar Abrego Garcia should not be detained before trial in the same wrongful-deportation episode that followed his return and criminal case.',
        },
      ),
      makeBenchmarkItem(
        'abrego_garcia_wrongful_deportation_episode',
        'reuters-abrego-lawsuit-dismissal-bid',
        "Trump administration seeks to dismiss Kilmar Abrego Garcia's lawsuit over deportation",
        'abrego-lawsuit-dismissal-bid-reuters',
        1_749_859_200_000,
        {
          publisher: 'Reuters',
          url: 'https://www.reuters.com/world/us/trump-administration-seeks-dismiss-kilmar-abrego-garcias-lawsuit-over-deportation-2025-06-12/',
          canonicalUrl:
            'https://www.reuters.com/world/us/trump-administration-seeks-dismiss-kilmar-abrego-garcias-lawsuit-over-deportation-2025-06-12/',
          entity_keys: [
            'abrego_garcia_wrongful_deportation_episode',
            'kilmar_abrego_garcia',
            'wrongful_deportation_case',
            'pretrial_detention',
            'el_salvador_return',
          ],
          cluster_text:
            'The Trump administration sought to dismiss Kilmar Abrego Garcia lawsuit over his deportation in the same continuing legal episode that later reached pretrial-detention rulings after his return.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-rumeysa-ozturk',
    topic_id: 'fixture-known-event-ongoing-rumeysa-ozturk',
    items: [
      makeBenchmarkItem(
        'rumeysa_ozturk_detention_episode',
        'ap-ozturk-transfer-paused',
        "Appeals court pauses Tufts student's transfer to Vermont in immigration detention case",
        'ozturk-transfer-paused-ap',
        1_745_923_259_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/11369dd81ec5b95a7ad7c1d2a0c74f2d',
          canonicalUrl: 'https://apnews.com/article/11369dd81ec5b95a7ad7c1d2a0c74f2d',
          entity_keys: [
            'rumeysa_ozturk_detention_episode',
            'rumeysa_ozturk',
            'tufts_student',
            'immigration_detention',
            'vermont_transfer_fight',
          ],
          cluster_text:
            'A federal appeals court paused Rumeysa Ozturk transfer back to Vermont in the same detention-and-release legal fight over the Tufts student immigration case.',
        },
      ),
      makeBenchmarkItem(
        'rumeysa_ozturk_detention_episode',
        'ap-ozturk-return-ordered',
        'Appeals court orders ICE to return detained Turkish Tufts University student to Vermont',
        'ozturk-return-ordered-ap',
        1_746_631_464_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/709e6266f7bcebe5b281bdac3fb28e19',
          canonicalUrl: 'https://apnews.com/article/709e6266f7bcebe5b281bdac3fb28e19',
          entity_keys: [
            'rumeysa_ozturk_detention_episode',
            'rumeysa_ozturk',
            'tufts_student',
            'immigration_detention',
            'vermont_transfer_fight',
          ],
          cluster_text:
            'The appeals court then ordered ICE to return Rumeysa Ozturk to Vermont in the same detention challenge over her transfer and confinement in Louisiana.',
        },
      ),
      makeBenchmarkItem(
        'rumeysa_ozturk_detention_episode',
        'ap-ozturk-released',
        'Turkish Tufts University student released from Louisiana immigration detention center',
        'ozturk-released-ap',
        1_746_786_686_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/034d97a7e280c68a7d1fb6aa879ce87c',
          canonicalUrl: 'https://apnews.com/article/034d97a7e280c68a7d1fb6aa879ce87c',
          entity_keys: [
            'rumeysa_ozturk_detention_episode',
            'rumeysa_ozturk',
            'tufts_student',
            'immigration_detention',
            'vermont_transfer_fight',
          ],
          cluster_text:
            'Rumeysa Ozturk was released from detention as the latest development in the same detention-and-transfer episode involving the Tufts student and the Vermont court fight.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-mohsen-mahdawi',
    topic_id: 'fixture-known-event-ongoing-mohsen-mahdawi',
    items: [
      makeBenchmarkItem(
        'mohsen_mahdawi_detention_episode',
        'ap-mahdawi-arrested',
        'A Palestinian activist expecting a US citizenship interview is arrested instead by ICE in Vermont',
        'mahdawi-arrested-ap',
        1_744_664_841_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/fca7e73fe2cbd616c1eacf3bdececdbe',
          canonicalUrl: 'https://apnews.com/article/fca7e73fe2cbd616c1eacf3bdececdbe',
          entity_keys: [
            'mohsen_mahdawi_detention_episode',
            'mohsen_mahdawi',
            'columbia_student',
            'immigration_detention',
            'citizenship_interview_arrest',
          ],
          cluster_text:
            'Mohsen Mahdawi was arrested during a citizenship interview in Vermont, beginning the same detention episode that later brought court hearings and his release.',
        },
      ),
      makeBenchmarkItem(
        'mohsen_mahdawi_detention_episode',
        'ap-mahdawi-hearing-set',
        'Palestinian student remains detained in Vermont with a hearing set for next week',
        'mahdawi-hearing-set-ap',
        1_745_452_402_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/2078326229e424b722e837595a03a042',
          canonicalUrl: 'https://apnews.com/article/2078326229e424b722e837595a03a042',
          entity_keys: [
            'mohsen_mahdawi_detention_episode',
            'mohsen_mahdawi',
            'columbia_student',
            'immigration_detention',
            'citizenship_interview_arrest',
          ],
          cluster_text:
            'Mahdawi remained detained and got a court hearing date in the same Vermont detention episode that started with his arrest during the citizenship interview.',
        },
      ),
      makeBenchmarkItem(
        'mohsen_mahdawi_detention_episode',
        'ap-mahdawi-released',
        'A Palestinian student at Columbia is freed after his arrest at a citizenship interview',
        'mahdawi-released-ap',
        1_746_020_292_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/dd95ffff78464df1b485d5912f1b3fcb',
          canonicalUrl: 'https://apnews.com/article/dd95ffff78464df1b485d5912f1b3fcb',
          entity_keys: [
            'mohsen_mahdawi_detention_episode',
            'mohsen_mahdawi',
            'columbia_student',
            'immigration_detention',
            'citizenship_interview_arrest',
          ],
          cluster_text:
            'Mahdawi was released after a judge order in the same detention episode triggered by his arrest at the citizenship interview.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-ras-baraka',
    topic_id: 'fixture-known-event-ongoing-ras-baraka',
    items: [
      makeBenchmarkItem(
        'ras_baraka_delaney_hall_episode',
        'ap-baraka-arrested',
        'Newark mayor denies trespassing at immigration detention center following arrest',
        'baraka-arrested-ap',
        1_746_851_593_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/2b044ff4355240511e579275b8961270',
          canonicalUrl: 'https://apnews.com/article/2b044ff4355240511e579275b8961270',
          entity_keys: [
            'ras_baraka_delaney_hall_episode',
            'ras_baraka',
            'delaney_hall',
            'trespassing_charge',
            'alina_habba',
          ],
          cluster_text:
            'Ras Baraka denied trespassing after his arrest at Delaney Hall, beginning the same arrest-and-prosecution episode that later brought court proceedings and a lawsuit.',
        },
      ),
      makeBenchmarkItem(
        'ras_baraka_delaney_hall_episode',
        'ap-baraka-court-appearance',
        "Newark Mayor Ras Baraka says officials fingerprinting him second time tried to 'humiliate' him",
        'baraka-court-appearance-ap',
        1_747_279_373_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/4490e7ef9bc88e6b9261a0e548632ecd',
          canonicalUrl: 'https://apnews.com/article/4490e7ef9bc88e6b9261a0e548632ecd',
          entity_keys: [
            'ras_baraka_delaney_hall_episode',
            'ras_baraka',
            'delaney_hall',
            'trespassing_charge',
            'alina_habba',
          ],
          cluster_text:
            'Baraka described being fingerprinted again after a court hearing in the same Delaney Hall arrest and trespassing case.',
        },
      ),
      makeBenchmarkItem(
        'ras_baraka_delaney_hall_episode',
        'ap-baraka-sues-habba',
        "Newark mayor sues New Jersey's top federal prosecutor after arrest at immigration detention site",
        'baraka-sues-habba-ap',
        1_748_963_275_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/0d17f4adb136b9fefc02ea8b498124ed',
          canonicalUrl: 'https://apnews.com/article/0d17f4adb136b9fefc02ea8b498124ed',
          entity_keys: [
            'ras_baraka_delaney_hall_episode',
            'ras_baraka',
            'delaney_hall',
            'trespassing_charge',
            'alina_habba',
          ],
          cluster_text:
            'Baraka sued Alina Habba over the same Delaney Hall arrest and dropped trespassing case, extending that same arrest-and-prosecution episode into civil litigation.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-voice-of-america',
    topic_id: 'fixture-known-event-ongoing-voice-of-america',
    items: [
      makeBenchmarkItem(
        'voice_of_america_dismantling_episode',
        'ap-voa-blocks-firings',
        'Voice of America wins in court, for now, as judge blocks Trump administration from firing staff',
        'voa-blocks-firings-ap',
        1_743_201_273_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/a1ed0ad37917055a1565da5325bd4fd8',
          canonicalUrl: 'https://apnews.com/article/a1ed0ad37917055a1565da5325bd4fd8',
          entity_keys: [
            'voice_of_america_dismantling_episode',
            'voice_of_america',
            'us_agency_for_global_media',
            'kari_lake',
            'staff_firings',
          ],
          cluster_text:
            'A judge blocked the Trump administration from firing Voice of America staff in the same ongoing effort to dismantle VOA that later brought restoration orders and renewed job-cut fights.',
        },
      ),
      makeBenchmarkItem(
        'voice_of_america_dismantling_episode',
        'ap-voa-blocks-dismantling',
        'Federal judge blocks Trump administration from dismantling Voice of America',
        'voa-blocks-dismantling-ap',
        1_745_353_087_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/f30c48df0c16de622ec5fd99ee6c627c',
          canonicalUrl: 'https://apnews.com/article/f30c48df0c16de622ec5fd99ee6c627c',
          entity_keys: [
            'voice_of_america_dismantling_episode',
            'voice_of_america',
            'us_agency_for_global_media',
            'kari_lake',
            'staff_firings',
          ],
          cluster_text:
            'A federal judge blocked the broader dismantling of Voice of America in the same administration shutdown episode that began with staff cuts and continued through later compliance fights.',
        },
      ),
      makeBenchmarkItem(
        'voice_of_america_dismantling_episode',
        'ap-voa-restore-order-ignored',
        "Judge orders Trump administration to explain why order to restore Voice of America wasn't followed",
        'voa-restore-order-ignored-ap',
        1_754_013_262_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/b60d40621f41b2ff4460803de4e0142f',
          canonicalUrl: 'https://apnews.com/article/b60d40621f41b2ff4460803de4e0142f',
          entity_keys: [
            'voice_of_america_dismantling_episode',
            'voice_of_america',
            'us_agency_for_global_media',
            'kari_lake',
            'staff_firings',
          ],
          cluster_text:
            'The judge later demanded an explanation for the government failure to restore Voice of America operations in the same dismantling lawsuit.',
        },
      ),
      makeBenchmarkItem(
        'voice_of_america_dismantling_episode',
        'ap-voa-suspends-job-cuts',
        "Judge suspends Trump administration's plan to eliminate hundreds of Voice of America jobs",
        'voa-suspends-job-cuts-ap',
        1_759_190_759_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/253c1c08e767ab4a2340b58e896f88a8',
          canonicalUrl: 'https://apnews.com/article/253c1c08e767ab4a2340b58e896f88a8',
          entity_keys: [
            'voice_of_america_dismantling_episode',
            'voice_of_america',
            'us_agency_for_global_media',
            'kari_lake',
            'staff_firings',
          ],
          cluster_text:
            'A judge later suspended new mass job cuts at Voice of America in the same dismantling-and-restoration legal episode.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-harvard-foreign-students',
    topic_id: 'fixture-known-event-ongoing-harvard-foreign-students',
    items: [
      makeBenchmarkItem(
        'harvard_foreign_students_sanctions_episode',
        'ap-harvard-blocks-ban',
        'Federal judge blocks Trump administration from barring foreign student enrollment at Harvard',
        'harvard-blocks-ban-ap',
        1_748_092_422_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/94b65866c563e67a7a7a3c79e90144d6',
          canonicalUrl: 'https://apnews.com/article/94b65866c563e67a7a7a3c79e90144d6',
          entity_keys: [
            'harvard_foreign_students_sanctions_episode',
            'harvard_university',
            'foreign_students',
            'student_visa_sanctions',
            'allison_burroughs',
          ],
          cluster_text:
            'A judge blocked the Trump administration from barring Harvard from enrolling foreign students, starting the same legal episode over sanctions on Harvard international enrollment.',
        },
      ),
      makeBenchmarkItem(
        'harvard_foreign_students_sanctions_episode',
        'ap-harvard-extends-block',
        "Judge extends order suspending Trump's block on Harvard's incoming foreign students",
        'harvard-extends-block-ap',
        1_750_097_522_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/e098ce93756fe51c476037b0ff52fabe',
          canonicalUrl: 'https://apnews.com/article/e098ce93756fe51c476037b0ff52fabe',
          entity_keys: [
            'harvard_foreign_students_sanctions_episode',
            'harvard_university',
            'foreign_students',
            'student_visa_sanctions',
            'allison_burroughs',
          ],
          cluster_text:
            'The court extended its hold on the Harvard foreign-student block in the same sanctions dispute over international enrollment.',
        },
      ),
      makeBenchmarkItem(
        'harvard_foreign_students_sanctions_episode',
        'ap-harvard-blocks-hosting-effort',
        'Federal judge blocks Trump effort to keep Harvard from hosting foreign students',
        'harvard-blocks-hosting-effort-ap',
        1_750_449_434_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/9498074cfe5f1054a712b9c21d36c6c5',
          canonicalUrl: 'https://apnews.com/article/9498074cfe5f1054a712b9c21d36c6c5',
          entity_keys: [
            'harvard_foreign_students_sanctions_episode',
            'harvard_university',
            'foreign_students',
            'student_visa_sanctions',
            'allison_burroughs',
          ],
          cluster_text:
            'The court again blocked efforts to stop Harvard from hosting foreign students in the same continuing sanctions case over international enrollment.',
        },
      ),
    ],
  },
  {
    dataset_id: 'fixture-known-event-ongoing-yunseo-chung',
    topic_id: 'fixture-known-event-ongoing-yunseo-chung',
    items: [
      makeBenchmarkItem(
        'yunseo_chung_deportation_episode',
        'ap-chung-sues',
        "Columbia student protester who's lived in the US since age 7 sues to stop deportation order",
        'yunseo-chung-sues-ap',
        1_742_840_024_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/052280bfe4e8d4d07e98a681058340fe',
          canonicalUrl: 'https://apnews.com/article/052280bfe4e8d4d07e98a681058340fe',
          entity_keys: [
            'yunseo_chung_deportation_episode',
            'yunseo_chung',
            'columbia_student',
            'deportation_order',
            'ice_detention_fight',
          ],
          cluster_text:
            'Yunseo Chung sued to stop her deportation in the same Columbia student deportation episode that immediately led to court rulings on whether ICE could detain her.',
        },
      ),
      makeBenchmarkItem(
        'yunseo_chung_deportation_episode',
        'ap-chung-cant-be-detained',
        "Columbia student protester can't be detained for now as she fights deportation, judge rules",
        'yunseo-chung-cant-be-detained-ap',
        1_742_933_922_000,
        {
          publisher: 'AP News',
          url: 'https://apnews.com/article/2d7bd689b013b8bb6300fd6ab54de933',
          canonicalUrl: 'https://apnews.com/article/2d7bd689b013b8bb6300fd6ab54de933',
          entity_keys: [
            'yunseo_chung_deportation_episode',
            'yunseo_chung',
            'columbia_student',
            'deportation_order',
            'ice_detention_fight',
          ],
          cluster_text:
            'A judge then barred immigration detention of Yunseo Chung while the same deportation challenge played out.',
        },
      ),
    ],
  },
];

export const STORYCLUSTER_KNOWN_EVENT_ONGOING_PAIR_EXPECTATIONS: StoryClusterBenchmarkPairExpectation[] = [
  {
    case_id: 'known-event-ongoing-kennedy-closure-staff-cuts',
    dataset_id: 'fixture-known-event-ongoing-kennedy-center',
    left_source_id: 'pbs-kennedy-closure',
    right_source_id: 'ap-kennedy-staff-cuts',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-kennedy-staff-cuts-grenell-step-down',
    dataset_id: 'fixture-known-event-ongoing-kennedy-center',
    left_source_id: 'ap-kennedy-staff-cuts',
    right_source_id: 'ap-kennedy-grenell-step-down',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-kennedy-grenell-board-showdown',
    dataset_id: 'fixture-known-event-ongoing-kennedy-center',
    left_source_id: 'ap-kennedy-grenell-step-down',
    right_source_id: 'ap-kennedy-board-showdown',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-kennedy-interview-vs-board',
    dataset_id: 'fixture-known-event-ongoing-kennedy-center',
    left_source_id: 'pbs-kennedy-grenell-interview',
    right_source_id: 'ap-kennedy-board-showdown',
    expected_label: 'commentary_on_event',
  },
  {
    case_id: 'known-event-ongoing-fed-subpoena-backlash',
    dataset_id: 'fixture-known-event-ongoing-fed-powell',
    left_source_id: 'ap-fed-subpoena',
    right_source_id: 'ap-fed-backlash',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-fed-subpoena-quash',
    dataset_id: 'fixture-known-event-ongoing-fed-powell',
    left_source_id: 'ap-fed-subpoena',
    right_source_id: 'ap-fed-judge-quash',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-fed-backlash-quash',
    dataset_id: 'fixture-known-event-ongoing-fed-powell',
    left_source_id: 'ap-fed-backlash',
    right_source_id: 'ap-fed-judge-quash',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-fed-explainer-vs-quash',
    dataset_id: 'fixture-known-event-ongoing-fed-powell',
    left_source_id: 'ap-fed-what-we-know',
    right_source_id: 'ap-fed-judge-quash',
    expected_label: 'commentary_on_event',
  },
  {
    case_id: 'known-event-ongoing-flag-ban-vs-dismissal',
    dataset_id: 'fixture-known-event-ongoing-flag-burn-order-fallout',
    left_source_id: 'ap-flag-ban-order',
    right_source_id: 'ap-flag-case-dismissal',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-prank-charge-vs-dismissal',
    dataset_id: 'fixture-known-event-ongoing-teacher-prank-fallout',
    left_source_id: 'ap-prank-adult-charge',
    right_source_id: 'ap-prank-charges-dropped',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-willis-fees-vs-bills',
    dataset_id: 'fixture-known-event-ongoing-fani-willis-fallout',
    left_source_id: 'ap-willis-legal-fees',
    right_source_id: 'ap-willis-gop-bills',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-willis-bills-vs-wade-hearing',
    dataset_id: 'fixture-known-event-ongoing-fani-willis-fallout',
    left_source_id: 'ap-willis-gop-bills',
    right_source_id: 'ap-wade-hearing',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-willis-fees-vs-wade-hearing',
    dataset_id: 'fixture-known-event-ongoing-fani-willis-fallout',
    left_source_id: 'ap-willis-legal-fees',
    right_source_id: 'ap-wade-hearing',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-adams-doj-vs-hearing',
    dataset_id: 'fixture-known-event-ongoing-eric-adams-dismissal',
    left_source_id: 'reuters-adams-doj-dismissal',
    right_source_id: 'reuters-adams-judge-weighs-dismissal',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-adams-doj-vs-dismissed',
    dataset_id: 'fixture-known-event-ongoing-eric-adams-dismissal',
    left_source_id: 'reuters-adams-doj-dismissal',
    right_source_id: 'reuters-adams-case-dismissed',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-adams-hearing-vs-dismissed',
    dataset_id: 'fixture-known-event-ongoing-eric-adams-dismissal',
    left_source_id: 'reuters-adams-judge-weighs-dismissal',
    right_source_id: 'reuters-adams-case-dismissed',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-khalil-detention-vs-deportation-ruling',
    dataset_id: 'fixture-known-event-ongoing-mahmoud-khalil',
    left_source_id: 'reuters-khalil-new-jersey-challenge',
    right_source_id: 'reuters-khalil-can-be-deported',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-abrego-lawsuit-vs-pretrial-detention',
    dataset_id: 'fixture-known-event-ongoing-abrego-garcia',
    left_source_id: 'reuters-abrego-lawsuit-dismissal-bid',
    right_source_id: 'reuters-abrego-no-detention-before-trial',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-ozturk-transfer-vs-return',
    dataset_id: 'fixture-known-event-ongoing-rumeysa-ozturk',
    left_source_id: 'ap-ozturk-transfer-paused',
    right_source_id: 'ap-ozturk-return-ordered',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-ozturk-return-vs-release',
    dataset_id: 'fixture-known-event-ongoing-rumeysa-ozturk',
    left_source_id: 'ap-ozturk-return-ordered',
    right_source_id: 'ap-ozturk-released',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-mahdawi-arrest-vs-hearing',
    dataset_id: 'fixture-known-event-ongoing-mohsen-mahdawi',
    left_source_id: 'ap-mahdawi-arrested',
    right_source_id: 'ap-mahdawi-hearing-set',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-mahdawi-hearing-vs-release',
    dataset_id: 'fixture-known-event-ongoing-mohsen-mahdawi',
    left_source_id: 'ap-mahdawi-hearing-set',
    right_source_id: 'ap-mahdawi-released',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-baraka-arrest-vs-hearing',
    dataset_id: 'fixture-known-event-ongoing-ras-baraka',
    left_source_id: 'ap-baraka-arrested',
    right_source_id: 'ap-baraka-court-appearance',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-baraka-hearing-vs-lawsuit',
    dataset_id: 'fixture-known-event-ongoing-ras-baraka',
    left_source_id: 'ap-baraka-court-appearance',
    right_source_id: 'ap-baraka-sues-habba',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-voa-firing-vs-dismantling',
    dataset_id: 'fixture-known-event-ongoing-voice-of-america',
    left_source_id: 'ap-voa-blocks-firings',
    right_source_id: 'ap-voa-blocks-dismantling',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-voa-dismantling-vs-restore-order',
    dataset_id: 'fixture-known-event-ongoing-voice-of-america',
    left_source_id: 'ap-voa-blocks-dismantling',
    right_source_id: 'ap-voa-restore-order-ignored',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-voa-restore-order-vs-job-cuts',
    dataset_id: 'fixture-known-event-ongoing-voice-of-america',
    left_source_id: 'ap-voa-restore-order-ignored',
    right_source_id: 'ap-voa-suspends-job-cuts',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-harvard-ban-vs-extension',
    dataset_id: 'fixture-known-event-ongoing-harvard-foreign-students',
    left_source_id: 'ap-harvard-blocks-ban',
    right_source_id: 'ap-harvard-extends-block',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-harvard-extension-vs-hosting-order',
    dataset_id: 'fixture-known-event-ongoing-harvard-foreign-students',
    left_source_id: 'ap-harvard-extends-block',
    right_source_id: 'ap-harvard-blocks-hosting-effort',
    expected_label: 'same_developing_episode',
  },
  {
    case_id: 'known-event-ongoing-chung-lawsuit-vs-detention-order',
    dataset_id: 'fixture-known-event-ongoing-yunseo-chung',
    left_source_id: 'ap-chung-sues',
    right_source_id: 'ap-chung-cant-be-detained',
    expected_label: 'same_developing_episode',
  },
];
